stages:
    - test
    - build

test:
    stage: test
    script:
        - npm install -g grunt
        - yarn install
        - cp config-example.json config.json
        - grunt build
    tags:
        - nodejs

main:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeclient:main
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push registry.orr.noaa.gov/gnome/webgnomeclient:main
    tags:
        - shell
        - build
    only:
        - main
develop:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeclient:develop
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push registry.orr.noaa.gov/gnome/webgnomeclient:develop
    tags:
        - shell
        - build
    only:
        - develop

production:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/webgnomeclient:production
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push registry.orr.noaa.gov/gnome/webgnomeclient:production
    tags:
        - shell
        - build
    only:
        - production

