before_script: 
  - yum update -y
  - rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm && yum -y install nodejs
  # - yum install -y node npm
  - npm install -g grunt-cli
  - npm install

master: 
  script:
    - grunt install
    - cp config-example.json config.json
    - grunt build
  only: 
    - master

develop:
  script:
    - grunt install
    - cp config-example.json config.json
    - grunt build
