before_script: 
  - yum update -y
  - yum install -y node npm
  - npm install -g grunt-cli
  - npm install

master: 
  script:
    - grunt install
    - cp config-example.json config.json
    - grunt build
  only: 
    - master

develop:
  script:
    - grunt install
    - cp config-example.json config.json
    - grunt build
