test:
    script:
        - npm install
        - grunt install
        - cp config-example.json config.json
        - grunt build
    tags:
        - test
        - nodejs

master:
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient
    tags:
        - docker
        - build
    only:
        - master
develop:
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient:develop
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient:develop
    tags:
        - docker
        - build
    only:
        - develop

production:
    script:
        - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/webgnomeclient:production
        - docker push gitlab.orr.noaa.gov:5002/webgnomeclient:production
    tags:
        - docker
        - build
    only:
        - production

